// 'use client'

import type { Metadata } from 'next';
import '../../public/css/style.css';
// import {createPortal} from "react-dom";
// import ReduxProvider from './store/StoreProvider';
// import {GlobalModal} from '@/shared/ui/';
import ModalPortal from './portal/ModalPortal.client';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>
        <div className="wrap">
          {children}
          <ModalPortal />
        </div>
      </body>
    </html>
  );
}
