'use client'

// import type { Metadata } from "next";
import "./globals.css";
import "./css/style.css";

import ReduxProvider from "./StoreProvider";
import {GlobalModal} from '@/shared/ui/';

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html>
    <body>
      <ReduxProvider>
        <div className="wrap">
          {children}
        </div>
        <GlobalModal />
      </ReduxProvider>
    </body>
    </html>
);
}
